# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop
inherit_from: .rubocop_todo.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

  Include:
    - '**/Rakefile'
    - '**/config.ru'

  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/.*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'node_modules/**/*.*'
    - 'node_modules/**/.*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'gen-examples/examples/**/.*'
    - 'gen-examples/examples/**/*'

Naming/FileName:
  Exclude:
    - 'Gemfile'

# Turn off until we require 2.3 ruby
Style/SafeNavigation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Exclude:
    - 'spec/dummy/bin/spring'

Lint/HandleExceptions:
  Exclude:
    - 'spec/dummy/bin/rails'
    - 'spec/dummy/bin/rake'

Metrics/AbcSize:
  Max: 28

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 140

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 41

Metrics/ModuleLength:
  Max: 180

Style/GlobalVars:
  Exclude:
    - 'spec/dummy/config/environments/development.rb'
