default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306

development:
  <<: *default
  database: iron_dev
  username: root
  password:

test:
  <<: *default
  database: iron_test
  username: root
  password:
<<<<<<< HEAD

production:
  <<: *default
  database: <%= ENV['database_name'] %>
=======
>>>>>>> issue6-heroku-deployment
