default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

development:
  <<: *default
  database: iron_dev

test:
  <<: *default
  database: iron_test
